### PR TITLE
Created faker seed data and fixed random bugs closes #151

### LINKED ISSUE #151: Create Faker data (ORDERS REMAINING)

### PR DESCRIPTION
**Pull request by scottcrawford03**
Home page now has the upcoming events ordered and also show the most recently added events.

The faker data is in and it's generating a lot of Items and Users. We don't have Orders yet.

### CODE REVIEW

File: app/controllers/static_pages_controller.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@ def not_found
   end
 
   def index
-    @next_events = Event.active.last(5)
+    @next_events = Event.active.order(:date).first(5)
     @just_added = Event.active.order(:created_at).last(2)
```
Comment (KristaANelson) [inline app/controllers/static_pages_controller.rb:8]: good catch!

File: app/models/user.rb [hunk 2]
```diff
@@ -28,6 +28,7 @@ class User < ActiveRecord::Base
                                                account_activations),
                              message: "%{value} is reserved." }
   validates :street_1, :city, :state, :zipcode, presence: true
+  validates :slug, uniqueness: true
```
Comment (KristaANelson) [inline app/models/user.rb:31]: flash back to categorizations... hopefully slug gets to stay in for the long haul.

File: db/seeds.rb [hunk 3]
```diff
@@ -59,6 +59,10 @@ def generate_venues
        location: "New York, NY" },
      { name: "Providence Park",
        location: "Portland, OR" },
+     { name: "Soldier Field",
+       location: "Chicago, IL"  },
+     { name: "Emirates Stadium",
+       location: "London, England" },
```
Comment (KristaANelson) [inline db/seeds.rb:65]: Hubstub International... #hubstub #bigtime

File: db/seeds.rb [hunk 4]
```diff
@@ -145,14 +149,113 @@ def generate_events
     @event9.category = @categories[1]
 
     @event10 = Event.new(
-      title:        "Portland Timbers vs. Some Chumps",
-      description:  "Doesn't really matter who they play...",
+      title:        "Portland Timbers vs. Colorado Rapids",
+      description:  "The beautiful game",
```
Comment (KristaANelson) [inline db/seeds.rb:153]: so beautiful

File: db/seeds.rb [hunk 5]
```diff
@@ -145,14 +149,113 @@ def generate_events
...
+      title:        "New York Rangers vs. Chicago Blackhawks",
+      description:  "Nerds destroy robots",
+      date:         78.days.from_now.change({ hour: 3, min: 0, sec: 0  }),
+      approved:     true)
+    @event13.image      = @images[-1]
+    @event13.venue      = @venues[2]
+    @event13.category   = @categories[0]
+
+    @event14 = Event.new(
+      title:        "Chicago Bears vs. Green Bay Packers",
```
Comment (KristaANelson) [inline db/seeds.rb:188]: DAAAA BEARS!

File: db/seeds.rb [hunk 6]
```diff
@@ -145,14 +149,113 @@ def generate_events
...
+      date:         89.days.from_now.change({ hour: 1, min: 0, sec: 0  }),
+      approved:     true)
+    @event18.image      = @images[-1]
+    @event18.venue      = @venues[5]
+    @event18.category   = @categories[0]
+
+    @event18 = Event.new(
+      title:        "Les Miserables",
+      description:  "True beauty on the stage",
+      date:         45.days.from_now.change({ hour: 1, min: 0, sec: 0  }),
```
Comment (KristaANelson) [inline db/seeds.rb:235]: almost as beautiful as Rapids vs Timbers

File: db/seeds.rb [hunk 7]
```diff
@@ -163,9 +266,37 @@ def generate_events
...
     @event10.save
+    @event11.save
+    @event12.save
+    @event13.save
+    @event14.save
+    @event15.save
+    @event16.save
+    @event17.save
+    @event18.save
+    sleep 2
```
Comment (KristaANelson) [inline db/seeds.rb:277]: makes last two have a different created at time

**Comment by KristaANelson** [comment]
sooo much good data! Seed success! Good work :trophy:
