### PR TITLE
fixed the error messages and styled them closes #96

### LINKED ISSUE #96: Fix style on alert to match the rest of the site style

### PR DESCRIPTION
**Pull request by scottcrawford03**
changed the error messages to show full error messages and also styled them. :yellow_heart:

### CODE REVIEW

File: app/controllers/users_controller.rb [hunk 1]
```diff
@@ -6,8 +6,8 @@ def new
   def create
     user = User.create(user_params)
     if user.errors.any?
-      user.errors.each do |field, message|
-        flash["#{field}"] = "#{field}: #{message}"
+      user.errors.full_messages.each do |message|
```
Comment (nathanows) [inline app/controllers/users_controller.rb:9]: like the full messages :santa: :sparkles:

File: spec/integration/guest_view_spec.rb [hunk 2]
```diff
@@ -218,6 +218,19 @@
       expect(page).to have_content("$5.00")
       expect(page).to have_content("John Bob Smith")
     end
+
+    xit "doesn't show past events" do
```
Comment (nathanows) [inline spec/integration/guest_view_spec.rb:222]: why's this test skipped? the diff is a little weird, it makes it look like its a brand new commented out test.
