### PR TITLE
Fixed bugs throughout app with admin, seller, and event closes #28

### LINKED ISSUE #28: As an admin I have access to all seller functionality

### PR DESCRIPTION
**Pull request by scottcrawford03**
Admin can now list a ticket for a user.
Seller and Event now has all their tickets separated by events AND they disappear from the view if the items are in the session[:cart]

### CODE REVIEW

File: app/controllers/items_controller.rb [hunk 1]
```diff
@@ -10,12 +10,13 @@ def show
 
   def new
     @item = Item.new
-    @user = current_user
+    @user = current_user.admin? ? User.find_by(slug: params[:slug]) : current_user
```
Comment (bhargavisatpathy) [inline app/controllers/items_controller.rb:13]: Interesting!!!

**Comment by bhargavisatpathy** [comment]
Nice work!!!
